name: web3modal_flutter
description: The Web3Modal for WalletConnect built using Flutter.
version: 2.0.1
repository: https://github.com/WalletConnect/Web3ModalFlutter
publish_to: none # remove this when publish

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  flex_color_picker: ^3.2.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  hexagon: ^0.2.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  logger: ^1.4.0
  mockito: ^5.4.2
  qr_flutter_wc:
    git: 
      url: https://github.com/WalletConnect/qr.flutter.git
      ref: feature/modifying_painter
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  universal_io: ^2.2.0
  url_launcher: ^6.1.11
  w_common: ^3.0.0
  walletconnect_flutter_v2: ^2.1.4
  walletconnect_modal_flutter: ^2.1.11
  web3dart: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.4
  event: ^2.1.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dark/
    - assets/light/
    - assets/icons/
    - assets/help/
    - assets/png/
    - assets/png/2.0x/
    - assets/png/3.0x/

