name: Publish Internal (beta) to pub.dev

on:
  workflow_dispatch:
  # Publish a -betaXX version on pub.dev when a new tag (and release) with vX.X.X-betaYY is created
  # Always run this on master branch
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-beta)+[0-9]*'
      - '!v[0-9]+.[0-9]+.[0-9]+(-alpha)+[0-9]*'

jobs:
  publish:
    name: Publish Internal (beta) to pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      # Get package dependencies and generate files
      - name: Get package dependencies and generate files
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      # Get example app dependencies and generate files
      - name: Get example app dependencies and generate files
        working-directory: example
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      # Publish
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
      - name: Publish Package
        run: flutter pub publish -f
      - name: Notify Channel
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: 'INCOMING_WEBHOOK'
        with:
          payload: |-
            {
              "text":"🚀 Web3Modal Flutter *${{ github.ref_name }}* was just published at https://pub.dev/packages/web3modal_flutter"
            }